# Import the Packages

In [1]:
import numpy as np

import pandas as pd

import matplotlib.pyplot as plt

import seaborn as sns

# Read the Data

In [2]:
data_path = r"D:\Flight-Price-Prediction\data\flight_price.csv"

flights_df = pd.read_csv(data_path)

In [3]:
flights_df.head()

Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL   
1    Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR   
2  Jet Airways       9/06/2019     Delhi      Cochin  DEL → LKO → BOM → COK   
3       IndiGo      12/05/2019   Kolkata    Banglore        CCU → NAG → BLR   
4       IndiGo      01/03/2019  Banglore   New Delhi        BLR → NAG → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info  Price  
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897  
1    05:50         13:15   7h 25m     2 stops         No info   7662  
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882  
3    18:05         23:30   5h 25m      1 stop         No info   6218  
4    16:50         21:35   4h 45m      1 stop         No info  13302

**Observations**:
1. The `Airline` column has all the airline name categories.
2. The `Date_of_journey` column has all the entries as dates with the day first format.
3. The `Source` and `Destination` columns have city names and is categorical in nature.
4. The `Route` column marks the route of all the flights with information of the stops included along with it.
5. The `Dep Time` and `Arrival_Time` columns need some cleaning as they appear mixed types with time and date information.
6. The `Duration` column has the flight duration in both hours and minutes and has to be converted in a sinle format for better interpretation.
7. The `Total_Stops` is also categorical in natures and has values of total stops in text and should be converted to integer marking the number of stops the flight takes between its complete route.
8. The `Addtitional_info` column has to be investigated further.
9. The `Price` column is the target column and has price as integers.

In [4]:
print(f'The shape of the flights data has {flights_df.shape[0]} rows and {flights_df.shape[1]} columns')

The shape of the flights data has 10683 rows and 11 columns


In [5]:
flights_df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

In [6]:
flights_df.sample(20)

Airline Date_of_Journey    Source Destination  \
6985         Jet Airways       9/06/2019     Delhi      Cochin   
10402        Jet Airways      12/06/2019   Kolkata    Banglore   
1081         Jet Airways      12/06/2019     Delhi      Cochin   
3327   Multiple carriers       9/03/2019     Delhi      Cochin   
9631              IndiGo      03/03/2019  Banglore   New Delhi   
4177           Air India       6/06/2019     Delhi      Cochin   
1850           Air India      24/06/2019     Delhi      Cochin   
10068           SpiceJet      21/06/2019  Banglore       Delhi   
10103             IndiGo      21/04/2019  Banglore       Delhi   
7233           Air India       3/03/2019     Delhi      Cochin   
382               IndiGo       9/04/2019  Banglore       Delhi   
4416         Jet Airways      18/03/2019  Banglore   New Delhi   
9516              IndiGo       9/06/2019     Delhi      Cochin   
4290              IndiGo      24/06/2019   Kolkata    Banglore   
9561              IndiGo       1/04/2019  Banglore       Delhi   
8966              IndiGo       3/03/2019     Delhi      Cochin   
1955              IndiGo      15/04/2019   Kolkata    Banglore   
7785   Multiple carriers      27/05/2019     Delhi      Cochin   
6833   Multiple carriers       6/06/2019     Delhi      Cochin   
7916           Air India      21/06/2019  Banglore       Delhi   

                       Route Dep_Time  Arrival_Time Duration Total_Stops  \
6985   DEL → IDR → BOM → COK    09:35  04:25 10 Jun  18h 50m     2 stops   
10402        CCU → BOM → BLR    06:30         18:15  11h 45m      1 stop   
1081         DEL → BOM → COK    21:50  04:25 13 Jun   6h 35m      1 stop   
3327         DEL → BOM → COK    17:00  01:35 10 Mar   8h 35m      1 stop   
9631               BLR → DEL    16:55         19:45   2h 50m    non-stop   
4177   DEL → BHO → BOM → COK    20:00  19:15 07 Jun  23h 15m     2 stops   
1850   DEL → CCU → BOM → COK    14:25  19:15 25 Jun  28h 50m     2 stops   
10068              BLR → DEL    09:30         12:20   2h 50m    non-stop   
10103              BLR → DEL    18:25         21:20   2h 55m    non-stop   
7233   DEL → AMD → BOM → COK    19:45  19:15 04 Mar  23h 30m     2 stops   
382                BLR → DEL    16:55         19:55       3h    non-stop   
4416         BLR → BOM → DEL    07:00         12:25   5h 25m      1 stop   
9516         DEL → HYD → COK    06:50         16:10   9h 20m      1 stop   
4290               CCU → BLR    09:35         12:20   2h 45m    non-stop   
9561               BLR → DEL    16:55         19:55       3h    non-stop   
8966         DEL → BOM → COK    16:00  01:35 04 Mar   9h 35m      1 stop   
1955               CCU → BLR    09:35         12:20   2h 45m    non-stop   
7785         DEL → BOM → COK    11:40         21:00   9h 20m      1 stop   
6833         DEL → BOM → COK    10:00  01:30 07 Jun  15h 30m      1 stop   
7916               BLR → DEL    06:10         08:55   2h 45m    non-stop   

                   Additional_Info  Price  
6985                       No info  13292  
10402  In-flight meal not included   9899  
1081   In-flight meal not included  10262  
3327                       No info  14343  
9631                       No info   8855  
4177                       No info  11596  
1850                       No info  13381  
10068                      No info   3625  
10103                      No info   4823  
7233                       No info  12856  
382                        No info   4823  
4416                       No info  12284  
9516                       No info   6442  
4290                       No info   4804  
9561                       No info   4823  
8966                       No info  14871  
1955                       No info   4174  
7785                       No info   7005  
6833                       No info  13377  
7916                       No info   6961

In [7]:
# data types of columns in the data

flights_df.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
dtype: object

In [8]:
# info about the dataframe

flights_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64 
dtypes: int64(1), object(10)
memory usage: 918.2+ KB


In [9]:
# checking for missing values in the data

flights_df.isna().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [10]:
# filter out the rows that have missing values

(
    flights_df
    .loc[
     flights_df
    .isna()
    .any(axis=1)
    , :
    ]
    
)

Airline Date_of_Journey Source Destination Route Dep_Time  \
9039  Air India       6/05/2019  Delhi      Cochin   NaN    09:45   

      Arrival_Time Duration Total_Stops Additional_Info  Price  
9039  09:25 07 May  23h 40m         NaN         No info   7480

Index value `9039` has missing values in columns `Route` and `Total Stops`

In [11]:
# check for duplicate rows in the data

(
    flights_df
    .duplicated()
    .sum()
)

220

**220 rows in the data are duplicated**

In [12]:
(
    flights_df
    .loc[
    flights_df
    .duplicated(keep=False)
    ]
    .sort_values(by=['Date_of_Journey','Airline'])
    
)

Airline Date_of_Journey    Source Destination  \
6321    Air India      01/03/2019  Banglore   New Delhi   
9848    Air India      01/03/2019  Banglore   New Delhi   
572     Air India      03/03/2019  Banglore   New Delhi   
8168    Air India      03/03/2019  Banglore   New Delhi   
1552       IndiGo      03/03/2019  Banglore   New Delhi   
...           ...             ...       ...         ...   
8446  Jet Airways       9/06/2019     Delhi      Cochin   
8496  Jet Airways       9/06/2019     Delhi      Cochin   
8967  Jet Airways       9/06/2019     Delhi      Cochin   
9191  Jet Airways       9/06/2019     Delhi      Cochin   
9216  Jet Airways       9/06/2019     Delhi      Cochin   

                      Route Dep_Time  Arrival_Time Duration Total_Stops  \
6321  BLR → BOM → AMD → DEL    08:50  23:55 02 Mar   39h 5m     2 stops   
9848  BLR → BOM → AMD → DEL    08:50  23:55 02 Mar   39h 5m     2 stops   
572               BLR → DEL    21:10         23:55   2h 45m    non-stop   
8168              BLR → DEL    21:10         23:55   2h 45m    non-stop   
1552              BLR → DEL    16:55         19:45   2h 50m    non-stop   
...                     ...      ...           ...      ...         ...   
8446  DEL → NAG → BOM → COK    06:45  12:35 10 Jun  29h 50m     2 stops   
8496  DEL → JAI → BOM → COK    09:40  12:35 10 Jun  26h 55m     2 stops   
8967  DEL → JAI → BOM → COK    09:40  04:25 10 Jun  18h 45m     2 stops   
9191  DEL → JAI → BOM → COK    09:40  12:35 10 Jun  26h 55m     2 stops   
9216  DEL → IDR → BOM → COK    05:30  04:25 10 Jun  22h 55m     2 stops   

                  Additional_Info  Price  
6321                      No info  17135  
9848                      No info  17135  
572                       No info   7591  
8168                      No info   7591  
1552                      No info   8855  
...                           ...    ...  
8446                      No info  13376  
8496                      No info  13014  
8967  In-flight meal not included  10368  
9191  In-flight meal not included  10368  
9216                      No info  13292  

[415 rows x 11 columns]

In [13]:
(
    flights_df
    .rename(columns=str.lower)
    .columns
)

Index(['airline', 'date_of_journey', 'source', 'destination', 'route',
       'dep_time', 'arrival_time', 'duration', 'total_stops',
       'additional_info', 'price'],
      dtype='object')

## Airline

In [14]:
(
    flights_df['Airline']
    .str.replace('Vistara Premium economy','Vistara')
    .str.replace('Multiple carriers Premium economy','Multiple carriers')
    .str.replace('Jet Airways Business','Jet Airways')
    .str.strip()
    .str.replace(' ','_')
    .str.title()
    .unique()
)

array(['Indigo', 'Air_India', 'Jet_Airways', 'Spicejet',
       'Multiple_Carriers', 'Goair', 'Vistara', 'Air_Asia', 'Trujet'],
      dtype=object)

**Steps**
1. Replace the duplicate flight carriers and make them one.
2. Strip extra whitespaces from categories.
3. Replace the space between two words with "_".
4. Convert the words into Title case.

## Date_of_Journey

In [15]:
(
    pd.to_datetime(flights_df['Date_of_Journey'],dayfirst=True)
)

0       2019-03-24
1       2019-05-01
2       2019-06-09
3       2019-05-12
4       2019-03-01
           ...    
10678   2019-04-09
10679   2019-04-27
10680   2019-04-27
10681   2019-03-01
10682   2019-05-09
Name: Date_of_Journey, Length: 10683, dtype: datetime64[ns]

In [16]:
(
    pd.to_datetime(flights_df['Date_of_Journey'],dayfirst=True)
    .dt.day
)

0        24
1         1
2         9
3        12
4         1
         ..
10678     9
10679    27
10680    27
10681     1
10682     9
Name: Date_of_Journey, Length: 10683, dtype: int32

In [17]:
(
    pd.to_datetime(flights_df['Date_of_Journey'],dayfirst=True)
    .dt.month
)

0        3
1        5
2        6
3        5
4        3
        ..
10678    4
10679    4
10680    4
10681    3
10682    5
Name: Date_of_Journey, Length: 10683, dtype: int32

In [18]:
(
    pd.to_datetime(flights_df['Date_of_Journey'],dayfirst=True)
    .dt.year
    .agg(['min','max'])
)

min    2019
max    2019
Name: Date_of_Journey, dtype: int32

**Steps:**
1. Convert the column to datetime.
2. Extract the month and day information out of the datetime column.
3. Drop the original column after the extraction step.

## Source

In [19]:
(
    flights_df['Source']
    .unique()
)

array(['Banglore', 'Kolkata', 'Delhi', 'Chennai', 'Mumbai'], dtype=object)

In [20]:
(
    flights_df['Source']
    .value_counts()
)

Source
Delhi       4537
Kolkata     2871
Banglore    2197
Mumbai       697
Chennai      381
Name: count, dtype: int64

**No data cleaning steps to be performed in `Source` column**

## Destination

In [21]:
(
    flights_df['Destination']
    .unique()
)

array(['New Delhi', 'Banglore', 'Cochin', 'Kolkata', 'Delhi', 'Hyderabad'],
      dtype=object)

**Steps**
1. Merge the `New Delhi` and `Delhi` category together

In [22]:
(
    flights_df['Destination']
    .value_counts()
)

Destination
Cochin       4537
Banglore     2871
Delhi        1265
New Delhi     932
Hyderabad     697
Kolkata       381
Name: count, dtype: int64

In [23]:
(
    flights_df['Destination']
    .str.replace('New Delhi','Delhi')
    .value_counts()
)

Destination
Cochin       4537
Banglore     2871
Delhi        2197
Hyderabad     697
Kolkata       381
Name: count, dtype: int64

In [24]:
932 + 1265

2197

## Dep_Time

In [25]:
flights_df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

In [26]:
(
    pd.to_datetime(flights_df['Dep_Time'],format='mixed')
    .dt.time
)

0        22:20:00
1        05:50:00
2        09:25:00
3        18:05:00
4        16:50:00
           ...   
10678    19:55:00
10679    20:45:00
10680    08:20:00
10681    11:30:00
10682    10:55:00
Name: Dep_Time, Length: 10683, dtype: object

**Convert the column to datetime and extract the time information out of it**

In [27]:
(
    flights_df['Dep_Time']
    .str.contains(pat="[^0-9:]")
    .sum()
)

0

In [28]:
(
    flights_df['Dep_Time']
    .loc[lambda ser : ser
    .str.contains("[^0-9:]")]
)

Series([], Name: Dep_Time, dtype: object)

## Arrival Time

In [29]:
flights_df['Arrival_Time']

0        01:10 22 Mar
1               13:15
2        04:25 10 Jun
3               23:30
4               21:35
             ...     
10678           22:25
10679           23:20
10680           11:20
10681           14:10
10682           19:15
Name: Arrival_Time, Length: 10683, dtype: object

In [30]:
(
    pd.to_datetime(flights_df['Arrival_Time'],format='mixed')
    .dt.time
)

0        01:10:00
1        13:15:00
2        04:25:00
3        23:30:00
4        21:35:00
           ...   
10678    22:25:00
10679    23:20:00
10680    11:20:00
10681    14:10:00
10682    19:15:00
Name: Arrival_Time, Length: 10683, dtype: object

In [31]:
(
    flights_df['Arrival_Time']
    .str.split(" ",n=1,expand=True)
    .loc[:,1]
    .dropna()
    .unique()
)

array(['22 Mar', '10 Jun', '13 Mar', '02 Mar', '10 May', '04 Mar',
       '13 Jun', '28 May', '19 Mar', '07 May', '02 Jun', '16 Jun',
       '19 May', '16 May', '28 Jun', '02 May', '28 Mar', '19 Jun',
       '04 Apr', '25 Mar', '07 Mar', '25 Jun', '07 Jun', '25 May',
       '13 May', '16 Mar', '22 May', '10 Apr', '04 Jun', '20 May',
       '28 Apr', '25 Apr', '10 Mar', '19 Apr', '13 Apr', '02 Apr',
       '23 Mar', '22 Apr', '11 May', '07 Apr', '03 May', '08 Mar',
       '03 Mar', '05 Mar', '22 Jun', '04 May', '26 May', '16 Apr',
       '26 Jun', '29 May', '29 Jun', '29 Mar', '23 May', '17 Jun'],
      dtype=object)

## Duration

In [32]:
(
    flights_df['Duration']
    .loc[lambda ser: ~ser
    .str.contains("h")
    ]
    .index
)

Index([6474], dtype='int64')

- The index value 6474 contains the flight duration as 5 minutes which is not possible in a real world scenario

In [33]:
(
    flights_df.loc[[6474],:]
)

Airline Date_of_Journey  Source Destination                  Route  \
6474  Air India       6/03/2019  Mumbai   Hyderabad  BOM → GOI → PNQ → HYD   

     Dep_Time Arrival_Time Duration Total_Stops Additional_Info  Price  
6474    16:50        16:55       5m     2 stops         No info  17327

In [34]:
(
    flights_df['Duration']
    .loc[lambda ser: ~ser
    .str.contains("m")
    ]
)

2        19h
18       23h
33       22h
44       12h
53        3h
        ... 
10591    23h
10638    14h
10639    38h
10673    15h
10680     3h
Name: Duration, Length: 1031, dtype: object

In [35]:
def convert_to_minutes(ser):
    return (
        ser
        .str.split(" ",expand=True)
        .rename(columns={0:'hours',
                         1:'minutes'})
        .assign(
            hours = lambda df_: (
                df_['hours']
                .str.replace("h","")
                .astype(int)
                .mul(60)
            ),
            minutes= lambda df_:(
                df_['minutes']
                .str.replace("m","")
                .fillna("0")
                .astype(int)
            )
        )
        .sum(axis=1)
    )

## Total Stops

In [36]:
(
    flights_df['Total_Stops']
    .unique()
)

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [37]:
(
    flights_df['Total_Stops']
    .loc[
    lambda ser: ser.isna()
    ]
)

9039    NaN
Name: Total_Stops, dtype: object

In [38]:
(
    flights_df
    .loc[9039]
)

Airline               Air India
Date_of_Journey       6/05/2019
Source                    Delhi
Destination              Cochin
Route                       NaN
Dep_Time                  09:45
Arrival_Time       09:25 07 May
Duration                23h 40m
Total_Stops                 NaN
Additional_Info         No info
Price                      7480
Name: 9039, dtype: object

In [39]:
(
    flights_df['Total_Stops']
    .fillna("non-stop")
    .str.replace("non-stop","0")
    .str.replace(" stops?","",regex=True)
    .astype(int)
)

0        0
1        2
2        2
3        1
4        1
        ..
10678    0
10679    0
10680    0
10681    0
10682    2
Name: Total_Stops, Length: 10683, dtype: int32

## Additional_Info

In [40]:
(
    flights_df['Additional_Info']
    .unique()
)

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

**We can drop this column for now and train our model without this column**

## Price

In [41]:
(
    flights_df['Price']
    .isna().sum()
)

0

In [42]:
(
    flights_df['Price']
    .agg(['min','max'])
)

min     1759
max    79512
Name: Price, dtype: int64

In [43]:
(
    flights_df['Price']
    .dtype
)

dtype('int64')

-------

# Data Cleaning

In [44]:
def data_cleaning(df:pd.DataFrame):
    return (
        df
        .drop_duplicates()
        .rename(columns=str.lower)
        .assign(
            airline = lambda df_:df_.loc[:,'airline']
                                .str.replace('Vistara Premium economy','Vistara')
                                .str.replace('Multiple carriers Premium economy','Multiple carriers')
                                .str.replace('Jet Airways Business','Jet Airways')
                                .str.strip()
                                .str.replace(' ','_')
                                .str.title(),
            date_of_journey = lambda df_: pd.to_datetime(df_.loc[:,'date_of_journey'],dayfirst=True),
            day_of_journey = lambda df_: df_.loc[:,'date_of_journey'].dt.day,
            month_of_journey = lambda df_: df_.loc[:,'date_of_journey'].dt.month
        )
        .drop(columns='date_of_journey')
        .assign(
            destination = lambda df_: df_.loc[:,'destination']
                                    .str.replace('New Delhi','Delhi')
        )
        .drop(columns=['route'])
        .rename(columns={
            "dep_time": "departure_time"
        })
        .assign(
            departure_time = lambda df_: pd.to_datetime(df_.loc[:,'departure_time'],format='mixed')
                                        .dt.time,
            arrival_time = lambda df_: pd.to_datetime(df_.loc[:,'arrival_time'],format='mixed')
                                        .dt.time
        )
        .drop(index=[6474])
        .assign(
            duration = lambda df_: df_['duration'].pipe(convert_to_minutes),
            total_stops = lambda df_: (
                df_['total_stops']
                .fillna("non-stop")
                .str.replace("non-stop","0")
                .str.replace(" stops?","",regex=True)
                .astype(int)
            )
        )
        .drop(columns='additional_info')
    )

In [45]:
cleaned_data = data_cleaning(flights_df)

cleaned_data

airline    source destination departure_time arrival_time  \
0           Indigo  Banglore       Delhi       22:20:00     01:10:00   
1        Air_India   Kolkata    Banglore       05:50:00     13:15:00   
2      Jet_Airways     Delhi      Cochin       09:25:00     04:25:00   
3           Indigo   Kolkata    Banglore       18:05:00     23:30:00   
4           Indigo  Banglore       Delhi       16:50:00     21:35:00   
...            ...       ...         ...            ...          ...   
10678     Air_Asia   Kolkata    Banglore       19:55:00     22:25:00   
10679    Air_India   Kolkata    Banglore       20:45:00     23:20:00   
10680  Jet_Airways  Banglore       Delhi       08:20:00     11:20:00   
10681      Vistara  Banglore       Delhi       11:30:00     14:10:00   
10682    Air_India     Delhi      Cochin       10:55:00     19:15:00   

       duration  total_stops  price  day_of_journey  month_of_journey  
0           170            0   3897              24                 3  
1           445            2   7662               1                 5  
2          1140            2  13882               9                 6  
3           325            1   6218              12                 5  
4           285            1  13302               1                 3  
...         ...          ...    ...             ...               ...  
10678       150            0   4107               9                 4  
10679       155            0   4145              27                 4  
10680       180            0   7229              27                 4  
10681       160            0  12648               1                 3  
10682       500            2  11753               9                 5  

[10462 rows x 10 columns]

In [46]:
# save the cleaned data

cleaned_data.to_csv(r"D:\Flight-Price-Prediction\data\cleaned_data.csv")